project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "survey/index.qmd"
    - "analysis/index.qmd"
    - "results/index.qmd"

website:
  title: "消费行为调查分析平台"
  navbar:
    left:
      - text: "首页"
        href: index.qmd
      - text: "问卷设计"
        href: survey/index.qmd
      - text: "数据分析"
        href: analysis/index.qmd
      - text: "研究成果"
        href: results/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
