project:
  type: website
  output-dir: _site

website:
  title: "淘宝数据分析小店 - 专业数据分析服务"
  navbar:
    left:
      - text: "首页"
        href: index.qmd
      - text: "服务介绍"
        href: services.qmd
      - text: "关于我们"
        href: about.html
      - text: "案例展示"
        href: cases.html
      - text: "联系我们"
        href: contact.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
